### ISSUE TITLE
MustUseNamedParams is not registered in SlackIssueRegistry

### ISSUE THREAD

**Issue by utwyko** [slackhq/slack-lints#254]
Not sure if this intended or not but wanted to call it out in case this was accidentally missed. The `MustUseNamedParams` issue from [MustUseNamedParamsDetector](https://github.com/slackhq/slack-lints/blob/main/slack-lint-checks/src/main/java/slack/lint/MustUseNamedParamsDetector.kt) is not registered in the [SlackIssueRegistry](https://github.com/slackhq/slack-lints/blob/main/slack-lint-checks/src/main/java/slack/lint/SlackIssueRegistry.kt). So for folks just including the artifact this check is not run.

Thanks for publishing these lint checks publicly, great work!

**Comment by ZacSweers** [comment]
Thanks! Fix is out in 0.7.1 now
